import { Role } from 'src/enums/roles.enum';
const teacher = Role.TEACHER;
const admin = Role.ADMIN;
const user = Role.USER;

export const usersMock = [
  {
    name: 'John Doe',
    email: 'john.doe@example.com',
    password: '45679654',
    idNumber: '45679654',
    role: teacher,
  },
  {
    name: 'Alice Smith',
    email: 'alice.smith@example.com',
    password: 'Alice1234$',
    idNumber: '37659083',
    role: admin,
  },
  {
    name: 'Juan Perez',
    email: 'juan.perez@example.com',
    idNumber: '87654728',
    password: 'Password123!',
    role: user,
  },
  {
    name: 'Maria Lopez',
    email: 'maria.lopez@example.com',
    idNumber: '87654321',
    password: 'Password123!',
    role: user,
  },
  {
    name: 'Carlos Ruiz',
    email: 'carlos.ruiz@example.com',
    idNumber: '23456789',
    password: 'Password123!',
    role: user,
  },
  {
    name: 'Ana Martinez',
    email: 'ana.martinez@example.com',
    idNumber: '34567890',
    password: 'Password123!',
    role: user,
  },
  {
    name: 'Luis Hernandez',
    email: 'luis.hernandez@example.com',
    idNumber: '45678901',
    password: 'Password123!',
    role: user,
  },
  {
    name: 'Sofia Ramirez',
    email: 'sofia.ramirez@example.com',
    idNumber: '56789012',
    password: 'Password123!',
    role: user,
  },
  {
    name: 'Javier Fernandez',
    email: 'javier.fernandez@example.com',
    idNumber: '67890123',
    password: 'Password123!',
    role: user,
  },
  {
    name: 'Isabella Torres',
    email: 'isabella.torres@example.com',
    idNumber: '78901234',
    password: 'Password123!',
    role: user,
  },
  {
    name: 'Diego Gomez',
    email: 'diego.gomez@example.com',
    idNumber: '89012345',
    password: 'Password123!',
    role: user,
  },
  {
    name: 'Valeria Morales',
    email: 'valeria.morales@example.com',
    idNumber: '90123456',
    password: 'Password123!',
    role: user,
  },
  {
    name: 'Miguel Vargas',
    email: 'miguel.vargas@example.com',
    idNumber: '12345067',
    password: 'Password123!',
    role: user,
  },
  {
    name: 'Camila Rojas',
    email: 'camila.rojas@example.com',
    idNumber: '23456178',
    password: 'Password123!',
    role: user,
  },
  {
    name: 'Alejandro Castillo',
    email: 'alejandro.castillo@example.com',
    idNumber: '34567289',
    password: 'Password123!',
    role: user,
  },
  {
    name: 'Emilia Vega',
    email: 'emilia.vega@example.com',
    idNumber: '45678390',
    password: 'Password123!',
    role: user,
  },
  {
    name: 'Daniel Herrera',
    email: 'daniel.herrera@example.com',
    idNumber: '56789401',
    password: 'Password123!',
    role: user,
  },
  {
    name: 'Lucia Perez',
    email: 'lucia.perez@example.com',
    idNumber: '67890512',
    password: 'Password123!',
    role: user,
  },
  {
    name: 'Mateo Diaz',
    email: 'mateo.diaz@example.com',
    idNumber: '78901623',
    password: 'Password123!',
    role: user,
  },
  {
    name: 'Victoria Garcia',
    email: 'victoria.garcia@example.com',
    idNumber: '89012734',
    password: 'Password123!',
    role: user,
  },
  {
    name: 'Sebastian Lopez',
    email: 'sebastian.lopez@example.com',
    idNumber: '90123845',
    password: 'Password123!',
    role: user,
  },
  {
    name: 'Martina Chavez',
    email: 'martina.chavez@example.com',
    idNumber: '01234956',
    password: 'Password123!',
    role: user,
  },
];
