import { Level } from 'src/enums/level.enum';
import { Specialization } from 'src/enums/specializations.enum';

export const coursesMock = [
  {
    title: 'Travellers Course',
    language: 'English',
    specialization: Specialization.TRAVEL,
    level: Level.PRE_INTERMEDIATE,
    category: 'Basic',
    createdAt: new Date('2024-11-05T00:00:00.000Z'),
  },
  {
    title: 'Business English',
    language: 'English',
    specialization: Specialization.WORK,
    level: Level.ADVANCED,
    category: 'Premium',
    createdAt: new Date('2024-10-15T00:00:00.000Z'),
  },
  {
    title: 'Italian for Travellers',
    language: 'Italian',
    specialization: Specialization.TRAVEL,
    level: Level.ELEMENTARY,
    category: 'Basic',
    createdAt: new Date('2024-10-07T00:00:00.000Z'),
  },
  {
    title: 'German Conversation',
    language: 'German',
    specialization: Specialization.CONVERSATIONAL,
    level: Level.ELEMENTARY,
    category: 'Basic',
    createdAt: new Date('2024-10-20T00:00:00.000Z'),
  },
  {
    title: 'French Legal Language',
    language: 'French',
    specialization: Specialization.LEGAL,
    level: Level.PROFICIENCY,
    category: 'Premium',
    createdAt: new Date('2024-11-03T00:00:00.000Z'),
  },
  {
    title: 'Portuguese for Beginners',
    language: 'Portuguese',
    specialization: Specialization.GENERAL,
    level: Level.ELEMENTARY,
    category: 'Basic',
    createdAt: new Date('2024-10-22T00:00:00.000Z'),
  },
  {
    title: 'English Conversation',
    language: 'English',
    specialization: Specialization.CONVERSATIONAL,
    level: Level.ADVANCED,
    category: 'Basic',
    createdAt: new Date('2024-10-06T00:00:00.000Z'),
  },
  {
    title: 'Italian First Certificate',
    language: 'Italian',
    specialization: Specialization.WORK,
    level: Level.UPPER_INTERMEDIATE,
    category: 'Premium',
    createdAt: new Date('2024-11-04T00:00:00.000Z'),
  },
  {
    title: 'Advanced Business German',
    language: 'German',
    specialization: Specialization.WORK,
    level: Level.ADVANCED,
    category: 'Premium',
    createdAt: new Date('2024-10-04T00:00:00.000Z'),
  },
  {
    title: 'French for Travellers',
    language: 'French',
    specialization: Specialization.TRAVEL,
    level: Level.PRE_INTERMEDIATE,
    category: 'Basic',
    createdAt: new Date('2024-11-06T00:00:00.000Z'),
  },
];
